@ This file was generated by the program.

# Amsterdam
name = Amsterdam
country = The Netherlands
food = {
	(Stroopwafel, 5.76)
	(Thick Dutch Fries, 3.21)
	(Kibbeling, 8.65)
}
# End of Amsterdam

# Berlin
name = Berlin
country = Germany
food = {
	(Pretzels, 4)
	(Apfelstrudel, 6.25)
	(Berliner Pfannkuche, 8.23)
	(Schnitzel, 9.79)
}
# End of Berlin

# Brussels
name = Brussels
country = Belgium
food = {
	(Waterzooi, 6.45)
	(Luikse Siroop, 4.98)
	(Mosselen-friet, 4.45)
	(Speculoos, 2.79)
}
# End of Brussels

# Budapest
name = Budapest
country = Hungary
food = {
	(Goulash, 8.43)
	(Stuffed Cabbage, 6.99)
	(Smoked Meat, 12.99)
	(Dobos Torta, 2.79)
}
# End of Budapest

# Hamburg
name = Hamburg
country = Germany
food = {
	(Hamburger Hummersuppe, 6.46)
	(Knackwurst, 9.99)
	(Krabbentoast, 6.92)
	(Franzbrötchen, 12.74)
}
# End of Hamburg

# Lisbon
name = Lisbon
country = Portugal
food = {
	(Bacalhau, 5.49)
	(Caldeirada, 7.63)
	(Alcatra, 18.66)
}
# End of Lisbon

# London
name = London
country = England
food = {
	(Yorkshire Pudding, 3.49)
	(Bangers & Mash, 6.63)
	(Sticky Toffee Pudding, 5.66)
}
# End of London

# Madrid
name = Madrid
country = Spain
food = {
	(Bocata de Calamares, 6.96)
	(Oreja a la Plancha, 11.85)
	(Caracoles a la Madrileña, 6.94)
}
# End of Madrid

# Paris
name = Paris
country = France
food = {
	(Caramels, 4.76)
	(Bordier Butter, 5.65)
	(Baguette, 4.99)
	(Pain au Chocolat, 4.69)
}
# End of Paris

# Prague
name = Prague
country = The Czech Republic
food = {
	(Beef Steak Tartare, 18.76)
	(Kulajda, 6.89)
	(Svickova, 5.98)
	(Roast Duck, 14.69)
}
# End of Prague

# Rome
name = Rome
country = Italy
food = {
	(Spaghetti alla Carbonara, 6.73)
	(Bruschetta, 4.85)
	(Scaloppine, 12.99)
	(Rigatoni con la Pajata, 8.79)
	(Carciofi alla Giudia, 15.99)
}
# End of Rome

# Stockholm
name = Stockholm
country = Sweden
food = {
	(Raggmunk, 6.75)
	(Gravad Lax, 13.76)
	(Husmanskost, 7.98)
}
# End of Stockholm

# Vienna
name = Vienna
country = Austria
food = {
	(Wiener Schnitzel, 4.94)
	(Kaiserschmarrn, 7.53)
	(Sachertorte, 5.85)
}
# End of Vienna

